2020-07-07 13:17:14,441 ERROR: Exception on /index [GET] [in /home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/cesare/PycharmProjects/flask/app/routes.py", line 57, in index
    return render_template('index.html', title='Front', posts=posts, form=form)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/cesare/PycharmProjects/flask/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/cesare/PycharmProjects/flask/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/cesare/PycharmProjects/flask/app/templates/index.html", line 25, in block "content"
    {% include '_post.html' %}
  File "/home/cesare/PycharmProjects/flask/app/templates/_post.html", line 7, in top-level template code
    <td><img src="{{user.avatar(36)}}"></td>
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2020-07-07 13:20:20,365 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 13:23:06,662 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 13:23:49,003 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 13:25:20,196 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 13:43:37,594 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 13:50:21,981 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 14:00:40,435 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 14:11:50,897 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 14:12:45,768 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 14:23:35,125 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 14:30:20,797 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 14:35:53,316 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 14:35:58,065 ERROR: Exception on /user/admin [GET] [in /home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/cesare/PycharmProjects/flask/app/routes.py", line 171, in user
    page = request.args('page', 1, type=int)
TypeError: 'ImmutableMultiDict' object is not callable
2020-07-07 14:36:35,184 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 14:36:38,192 ERROR: Exception on /user/admin [GET] [in /home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/cesare/PycharmProjects/flask/app/routes.py", line 172, in user
    posts = user.psots.order_by(Post.timestamp.desc()).paginate(
AttributeError: 'User' object has no attribute 'psots'
2020-07-07 14:36:51,776 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 14:36:53,540 ERROR: Exception on /user/admin [GET] [in /home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/cesare/PycharmProjects/flask/app/routes.py", line 182, in user
    return render_template('user.html',title='User', user=user, posts=posts, form=form)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/cesare/PycharmProjects/flask/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/cesare/PycharmProjects/flask/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/cesare/PycharmProjects/flask/app/templates/user.html", line 33, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
