2020-07-07 14:41:56,633 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 14:42:55,284 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:46]
2020-07-07 15:38:42,440 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:47]
2020-07-07 15:43:19,768 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:47]
2020-07-07 15:52:05,910 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:47]
2020-07-07 15:55:33,685 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:47]
2020-07-07 16:04:05,225 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:47]
2020-07-07 16:04:10,934 ERROR: Exception on /login [GET] [in /home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cesare/PycharmProjects/flask/app/routes.py", line 130, in login
    return render_template('login.html', title='Login', form=form)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/cesare/PycharmProjects/flask/app/templates/login.html", line 1, in top-level template code
    {%extends "base.html" %}
  File "/home/cesare/PycharmProjects/flask/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/cesare/PycharmProjects/flask/app/templates/login.html", line 34, in block "content"
    <a href="{{ url_for('reset_password_request')}}">Click here to reset it!</a>
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2020-07-07 16:18:15,027 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:47]
2020-07-07 17:07:33,734 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:47]
2020-07-07 17:08:10,236 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:47]
2020-07-07 17:08:16,433 ERROR: Exception on /reset_password_request [GET] [in /home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cesare/PycharmProjects/flask/app/routes.py", line 269, in reset_password_request
    if current_user.is_authenticated():
TypeError: 'bool' object is not callable
2020-07-07 17:09:11,665 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:47]
2020-07-07 17:11:32,075 ERROR: Exception on /reset_password_request [POST] [in /home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cesare/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cesare/PycharmProjects/flask/app/routes.py", line 275, in reset_password_request
    send_password_reset_email(user)
  File "/home/cesare/PycharmProjects/flask/app/email.py", line 17, in send_password_reset_email
    text_body=render_template('email/reset_password.txt', user=user, token=token),
NameError: name 'token' is not defined
2020-07-07 17:12:34,922 INFO: Microblog startup [in /home/cesare/PycharmProjects/flask/app/__init__.py:47]
